### ISSUE TITLE
Create docs on ingress control

### ISSUE THREAD

**Issue by some-natalie** [some-natalie/kubernoodles#80]
Create some documentation around using an ingress controller.

General outline ideas

- [ ] start with HTTP only
- [ ] add caching with persistent data volume
- [ ] add TLS using lets-encrypt
